"""empty message

Revision ID: 872827fc313b
Revises: b092b19c0261
Create Date: 2024-04-19 16:25:06.621221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872827fc313b'
down_revision = 'b092b19c0261'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
